AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: HelloWorlkChrisWebsite
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

