AWSTemplateFormatVersion: "2010-09-09"
Description: Creation of a fell Stack Deployment with Infrastructure
Mappings:
    RegionMap:
        us-east-1:
            AMI: ami-04681a1dbd79675a5
        us-east-2:
            AMI: ami-0b59bfac6be064b78
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.1.0.0/16
            EnableDnsSupport: true
            EnableDnsHostnames: true
            InstanceTenancy: default
            Tags:
                - Key: Name
                  Value: WebVpc
    InternetGateway:
        Type: AWS::EC2::InternetGateway
    VPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref VPC
            InternetGatewayId: !Ref InternetGateway
    SubnetWeb01:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-2a
            VpcId: !Ref VPC
            CidrBlock: 10.1.1.0/24
            MapPublicIpOnLaunch: true
    SubnetWeb02:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-2b
            VpcId: !Ref VPC
            CidrBlock: 10.1.2.0/24
            MapPublicIpOnLaunch: true
    SubnetWeb03:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-2c
            VpcId: !Ref VPC
            CidrBlock: 10.1.3.0/24
            MapPublicIpOnLaunch: true
    RouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
    InternetRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGateway
        Properties:
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway
            RouteTableId: !Ref RouteTable
    SubnetWeb01RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref SubnetWeb01
    SubnetWeb02RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref SubnetWeb02
    SubnetWeb03RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref SubnetWeb03
    LoadBalancer:  # Application Load Balancer
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            SecurityGroups:
                !Ref ALBLoadBalancer
            Subnets:
                !Ref SubnetIDs
    LoadBalancerListner: # Port 80 Listner for ALB
        Type: AWS::ElasticLoadBalancingV2::Listener
        Propertiees:
            LoadBalancerARN: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP
            DefaultActions:
                - Type: foreward
                  TargetGroupARN: !Ref TargetGroup
    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Port: 80
            Protocol: HTTP
            VpcId: !Ref VPC
    AutoScalingGroup:
            Type: AWS::AutoScaling::AutoScalingGroup
            Properties:
                AvailabilityZones: !GetAzs
